# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ca',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Last modified', null=True, verbose_name='Last modified'),
        ),
    ]
