# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0002_ca_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='subca',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Last modified', null=True, verbose_name='Last modified'),
        ),
    ]
