version: '2'

volumes:
  pizza_postgres_data: {}
  pizza_postgres_backup: {}
  pizza_elastic_data: {}
  pizza_ca_root_data: {}

services:
  pizza-postgres:
    build: ./compose/postgres
    volumes:
      - pizza_postgres_data:/var/lib/postgresql/data
      - pizza_postgres_backup:/backups
    env_file: .env

  pizza-elastic:
    image: elasticsearch:1.7
    volumes:
      - pizza_elastic_data:/usr/share/elasticsearch/data


  pizza-django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    volumes:
      - pizza_ca_root_data:/ca_root
    user: django
    depends_on:
      - pizza-postgres
      - pizza-redis
      - pizza-elastic
    command: /gunicorn.sh
    env_file: .env

  pizza-nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    depends_on:
      - pizza-django

    ports:
      - "0.0.0.0:8888:80"


  pizza-redis:
    image: redis:latest

