# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ca', '0003_subca_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CN', models.CharField(help_text='Common Name', max_length=255, verbose_name='Common Name')),
                ('T', models.CharField(blank=True, help_text='Title', max_length=255, null=True, verbose_name='Title')),
                ('GN', models.CharField(help_text='Given name', max_length=255, verbose_name='Given name')),
                ('SN', models.CharField(help_text='Surname', max_length=255, verbose_name='Surname')),
                ('E', models.CharField(help_text='Email address', max_length=255, verbose_name='Email address')),
                ('O', models.CharField(help_text='Organization', max_length=255, verbose_name='Organization')),
                ('OU', models.CharField(blank=True, help_text='Organizational unit', max_length=255, null=True, verbose_name='Organizational unit')),
                ('ST', models.CharField(blank=True, help_text='State or Province', max_length=255, null=True, verbose_name='State or Province')),
                ('L', models.CharField(blank=True, help_text='Locality name', max_length=255, null=True, verbose_name='Locality name')),
                ('C', models.CharField(choices=[('ES', 'Spain'), ('IT', 'Italy'), ('GB', 'United Kingdom'), ('US', 'United States')], default='ES', help_text='Country', max_length=2, verbose_name='Country')),
                ('serialNumber', models.CharField(help_text='Serial number', max_length=255, verbose_name='Serial number')),
                ('cert_format', models.CharField(choices=[('P12', 'pkcs#12'), ('PEM', 'pem encoded')], default='P12', help_text='Certificate format', max_length=3, verbose_name='Certificate format')),
                ('csr', models.TextField(blank=True, help_text='Certificate format', null=True, verbose_name='Certificate format')),
                ('not_before', models.DateTimeField(blank=True, help_text='Not before', null=True, verbose_name='Not before')),
                ('not_after', models.DateTimeField(blank=True, help_text='Not after', null=True, verbose_name='Not after')),
                ('revoked_on', models.DateTimeField(blank=True, help_text='Revoked on', null=True, verbose_name='Revoked on')),
                ('crl_reason', models.CharField(blank=True, choices=[('unspecified', 'Unspecified'), ('keyCompromise', 'Key compromise'), ('caCompromise', 'CA compromise'), ('affiliationChanged', 'Affiliation changed'), ('superseded', 'Superseded'), ('cessationOfOperation', 'Cessation of operation'), ('certificateHold', 'Certificate hold'), ('removeFromCRL', 'Remove from CRL')], help_text='Reason', max_length=255, null=True, verbose_name='Reason')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Last modified', null=True, verbose_name='Last modified')),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='new', help_text='Current CA status', max_length=10, verbose_name='CA Status')),
                ('issuer', models.ForeignKey(help_text='Issuer', on_delete=django.db.models.deletion.CASCADE, to='ca.SubCA', verbose_name='Issuer')),
            ],
            options={
                'permissions': (('can_search_identity', 'Can search for certificates'), ('can_generate_identity', 'Can generate certificates'), ('can_pkcs12_identity', 'Can download pkcs#12 bundle'), ('can_revoke_identity', 'Can revoke certificates')),
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CN', models.CharField(help_text='Common Name', max_length=255, verbose_name='Common Name')),
                ('O', models.CharField(help_text='Organization', max_length=255, verbose_name='Organization')),
                ('OU', models.CharField(blank=True, help_text='Organizational unit', max_length=255, null=True, verbose_name='Organizational unit')),
                ('ST', models.CharField(blank=True, help_text='State or Province', max_length=255, null=True, verbose_name='State or Province')),
                ('L', models.CharField(blank=True, help_text='Locality name', max_length=255, null=True, verbose_name='Locality name')),
                ('C', models.CharField(choices=[('ES', 'Spain'), ('IT', 'Italy'), ('GB', 'United Kingdom'), ('US', 'United States')], default='ES', help_text='Country', max_length=2, verbose_name='Country')),
                ('E', models.CharField(blank=True, help_text='Email address', max_length=255, null=True, verbose_name='Email address')),
                ('csr', models.TextField(blank=True, help_text='Certificate format', null=True, verbose_name='Certificate format')),
                ('not_before', models.DateTimeField(blank=True, help_text='Not before', null=True, verbose_name='Not before')),
                ('not_after', models.DateTimeField(blank=True, help_text='Not after', null=True, verbose_name='Not after')),
                ('revoked_on', models.DateTimeField(blank=True, help_text='Revoked on', null=True, verbose_name='Revoked on')),
                ('crl_reason', models.CharField(blank=True, choices=[('unspecified', 'Unspecified'), ('keyCompromise', 'Key compromise'), ('caCompromise', 'CA compromise'), ('affiliationChanged', 'Affiliation changed'), ('superseded', 'Superseded'), ('cessationOfOperation', 'Cessation of operation'), ('certificateHold', 'Certificate hold'), ('removeFromCRL', 'Remove from CRL')], help_text='Reason', max_length=255, null=True, verbose_name='Reason')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Last modified', null=True, verbose_name='Last modified')),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='new', help_text='Current CA status', max_length=10, verbose_name='CA Status')),
                ('issuer', models.ForeignKey(help_text='Issuer', on_delete=django.db.models.deletion.CASCADE, to='ca.SubCA', verbose_name='Issuer')),
            ],
            options={
                'permissions': (('can_search_server', 'Can search for certificates'), ('can_generate_server', 'Can generate certificates'), ('can_revoke_server', 'Can revoke certificates')),
            },
        ),
    ]
